config/routes.rb
Rails.application.routes.draw do
  resources :players
  root 'home#index'
  get "/home/play/:name", to: "home#play"
  get "/play_game/:name", to: "home#play_game"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord

    def make_choice
        ["rock", "paper", "scissors"].sample
    end

    def choice
        @choice ||= make_choice
    end

end

app/models/rock_paper_scissors.rb
class RockPaperScissors
    attr_accessor :person_1, :person_2
        def initialize(player_1, player_2)
        @person_1 = player_1
        @person_2 = player_2
        end
  
        def play_round()
          outcome = "You played #{person_1.choice} and Computer played #{person_2.choice}. "
          combo = { "scissors" => "paper", "paper" => "rock", "rock" => "scissors" }
          if person_1.choice == person_2.choice
            outcome + "It's a draw!"
          elsif combo[person_1.choice] == person_2.choice
            outcome + "#{person_1.name} won!"
          else
            outcome + "#{person_2.name} won!"
          end
        end
end
 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def play
    @player = Player.find_by(name: params[:name])
  end

  def play_game 
    @player_1 = Player.find_by(name: params[:name])
    @player_2 = Player.new(name: "Computer")
    @game = RockPaperScissors.new(@player_1, @player_2)
    @game.play_round
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: %i[ show edit update destroy ]

  # GET /players or /players.json
  def index
    @players = Player.all
  end

  # GET /players/1 or /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players or /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: "Player was successfully created." }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1 or /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: "Player was successfully updated." }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1 or /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: "Player was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def player_params
      params.require(:player).permit(:name, :wins, :num_of_games)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <%= link_to "Rock Paper Scissors", root_path, class:"navbar-brand" %>
    <%#a class="navbar-brand" href="#">Rock Paper Scissors</a>%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <!--li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li-->
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>A Game of Rock Paper Scissors</h1>
<p>Register a new player or select one and let's begin</p>

<%= link_to 'New Player', new_player_path %>
<%= link_to 'Select Player', players_path %>

app/views/home/play.html.erb
<h1> Make your choice! </h1>
<br/>
<%= link_to 'ROCK', "/play_game/#{@player.name}", class: "btn btn-primary" %>

<!%= link_to 'PAPER', play_game_path, class: "btn btn-primary" %>

<!%= link_to 'SCISSORS', play_game_path, class: "btn btn-primary" %>

app/views/home/play_game.html.erb
<%= @game.play_round %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
    <title>RPSrails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "home/header" %>
    <div class = "container">
      <br/>
      <%= yield %>
    </div>
  </body>
</html>

app/views/players/_form.html.erb
<%= form_with(model: player) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
        <% player.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :wins %>
    <%= form.number_field :wins %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Players</h1>

<table class="table table-bordered">
  <thead class="table-light">
    <tr>
      <th>Name</th>
      <th>Wins</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= link_to player.name, "/home/play/#{player.name}" %></td>
        <td><%= player.wins %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>Wins:</strong>
  <%= @player.wins %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>